update_climate:
  description: Change the hvac mode of the given climate device.
  fields:
    enitity_id:
      description: The climates enitity_id
      example: climate.livingroom
    sensor_on:
      description: The climate will be off when this sensors is on.
      example: binary_sensor.livingroom_window
    sensor_off:
      description: The climate will be off when this sensors is off.
      example: binary_sensor.livingroom_climate_on
    sensor_presence:
      description: The climate will switch to active mode if this sensor is on.
      example: binary_sensor.someone_at_home
    heating_from_hour:
      description: Start time from which heating is to start
      example: 8
    heating_to_hour:
      description: End time to which the heating is to last.
      example: 17
    high_temp:
      description: Temperature for active hours.
      example: 24
    low_temp:
      description: Temperature for inactive hours.
      example: 20
